### PR TITLE
updated readme.md

### PR DESCRIPTION
**Pull request by pixobia**
please merge my request for hacktoberfest

### CODE REVIEW

**Comment by anurag-sep-01** [comment]
Hey try to run the project

**Comment by pixobia** [comment]
Can you please elaborate what exactly u want me to do as  i m a beiginner

**Comment by anurag-sep-01** [comment]
if you have new feature regarding this project, please raise issue/PR

**Review by anurag-sep-01 — CHANGES_REQUESTED** [review]
use project image and try to add

**Pull request closed without merging**
